### ISSUE TITLE
Not working on vagrant

### ISSUE THREAD

**Issue by wpram** [BetterErrors/better_errors#133]
I'm using vagrant in development mode, and I notice better_errors don't work on vagrant? I'm using Rails 3.2.12. Thanks

**Comment by simkessy** [comment]
@MOZGIII  your first comment you say use it with parameters, then you're second comment you don't use parameters. 

Can you be specific? I'm having issues deploying this in production. It's running the initializer file and saying uninitialized constant BetterErrors. This is because the gem doesn't get installed in Production but the init file is looking for `BetterErrors`. Not sure how to proceed without doing something like this: 

BetterErrors::Middleware.allow_ip! "10.0.2.2" if Rails.env == :development

But that doesn't seem to work in Dev.

**Comment by MOZGIII** [comment]
@simkessy I think I can help you sort it out. But I need full error log, can you make a pastebin?

**Comment by MOZGIII** [comment]
@kmontag I figured out a solution that uses SSH peer address, it's on the wiki, at the very end of the page: https://github.com/charliesome/better_errors/wiki

**Comment by simkessy** [comment]
@MOZGIII  hey, this is the pastebin http://pastebin.com/mYtLctWX

This is what I have in the config:
```
# Allow usage on Vagrant
BetterErrors::Middleware.allow_ip! "10.0.2.2" if defined?(BetterErrors) && Rails.env == :development
```

**Comment by MOZGIII** [comment]
Oh, well, that's strange. It works for me, though. Could you please put your repo on Github, or just pastebin `cat config/initializers/better_errors.rb` and then `git status`?

**Comment by simkessy** [comment]
Hey, that line above is actually the only thing I have in the better_errors.rb initializer

**Comment by MOZGIII** [comment]
My guess is that you've just got something else set up not right, which leads to this weird problem. If you run this code on a local machine in production - does it work the same way?
Anyways though, a workaround for this particlular issue (I don't really understand for now why does it happen) is to just move it out to development environment file and to the job in there. You can try searching on it online, and this should do the trick.
However, I sencirely think you have something wrong with the overall setup: maybe you've just messed up the git, or editing the other file (I've seen people actually doing it), or sth like that. You can just try doublechecking everything else. The absolute worst thing you could have here is to not use brackets around the argument of `defined?`, since this is explained in this very issue in previous discussion.

**Comment by simkessy** [comment]
Alright, i'll keep looking around and try to figure it out, thanks.

**Comment by MOZGIII** [comment]
Yes. You can try using runnung `ruby config/initializers/better_errors.rb` to verify if it works, and that's what I did. The first statement (`defines?` check) in the `if` is false, so the whole if condition is false, so code is never executed. That's the idea. In production, the code path *should be the same*, and the second check is really an overkill, but that's there for safety.

**Comment by MOZGIII** [comment]
Again, `defined?` keyword is probably a bad thing to use anywhere, since it works on expressions, not values. More better thing to do is to precisely check for `BetterErrors` constant existance, which can be done with `Object.const_defined?('BetterErrors')` (haven't tried this one, but it should work).

**Comment by simkessy** [comment]
The simplest answer was to put the line in the development.rb file which doesn't get run in production as opposed to running it in an initializer and hoping the conditional figures it out.
