### ISSUE TITLE
Can't see errors in templates

### ISSUE THREAD

**Issue by manuelmeurer** [BetterErrors/better_errors#462]
With better_errors 2.7.0, when there's an error in one of my templates, this is what I see: https://take.ms/sCBE6
Obviously that's not really helpful because I don't see the actual error.

This is the same error with 2.6.0: https://take.ms/D9tpz
It correctly shows the error in the template.

**Comment by RobinDaugherty** [comment]
Thanks @manuelmeurer this is fixed in release 2.7.1 of Better Errors.

(In future, please attach screenshots directly in GitHub instead of linking to an external site. I downloaded and attached the ones you linked to in your PR description.)

**Comment by manuelmeurer** [comment]
Wow thanks for the super quick fix, @RobinDaugherty!

**Comment by manuelmeurer** [comment]
@RobinDaugherty With 2.7.1, I don't see the live shell for `ActionView::Template::Error` errors:

![ActionView:Template:Error at : 2020-05-15 17-09-43](https://user-images.githubusercontent.com/16672/82066097-44822d00-96cf-11ea-99f6-f411b0c9b45a.png)

With 2.6.0, it is there:

![RuntimeError+at++2020-05-15+16-47-13](https://user-images.githubusercontent.com/16672/82066129-506def00-96cf-11ea-907e-1fd2f9664f92.png)

For non-`ActionView::Template::Error` errors, 2.7.1 shows the live shell correctly.
Do you want me to create a new issue for this?

**Comment by RobinDaugherty** [comment]
Unfortunately, I noticed this after the new version was live. It's because the backtrace frame with the context from the template itself is only present in the `cause` of the exception that was raised. I've opened #466 for this. I've been working on a big change that will allow us to navigate between `cause`s (implementation of #464), which I hope to have out this week.
