### ISSUE TITLE
How to Link Editor wiki article is not clear

### ISSUE THREAD

**Issue by donquxiote** [BetterErrors/better_errors#471]
The list of supported editors is great, but it wasn't clear what variable I needed to pass to `BetterErrors.editor` to setup my editor. I'm more than happy to do the edit, but wanted to ask first and I wasn't sure where to open this since Github wiki's don't allow for pull requests.

Here's my proposal, add the approved symbol to the entries for each editor:

### Atom

Atom v1.23 [added support for open/file URLs](https://github.com/atom/atom/pull/15935).

Install the Shell Commands from within Atom and add the following to your shell config:

```sh
export EDITOR="atom"
```

### Atom
`:atom`

Atom v1.23 [added support for open/file URLs](https://github.com/atom/atom/pull/15935).

Install the Shell Commands from within Atom and add the following to your shell config:

```sh
export EDITOR="atom"
```

**Comment by RobinDaugherty** [comment]
Hi @donquxiote, the only configuration that should be necessary is to set `$EDITOR` in your shell/app environment.

You shouldn't add application code that configures Better Errors except as a last resort, since each developer might have a different editor preference. Since `$EDITOR` is used by _a lot_ of different tools, it's much better to set it in your profile based on your preferences.

I did add a link to the list of supported editors in code, but this really shouldn't need to be used.

**Comment by donquxiote** [comment]
Ah I see. The environment I'm working in is running in containers and doesn't have access to the local env, including the `$EDITOR` variable and I had to manually set it in the initializer. But that link you added would have answered my question when I had it, so that works. Thanks for looking at this!
